export const CREATE_NOTE = "NOTES/CREATE_NOTE";
export const DELETE_NOTE = "NOTES/DELETE_NOTE";
export const ARCHIVE_NOTE = "NOTES/ARCHIVE_NOTE";
export const UNARCHIVE_NOTE = "NOTES/UNARCHIVE_NOTE";
export const EDIT_NOTE = "NOTES/EDIT_NOTE";
